import React from 'react';

function Prescription({ prescription, patientData, onReset }) {
  return (
    <div className="card">
      <div className="card-header bg-success text-white">
        <h3 className="mb-0 d-flex align-items-center">
          <i className="bi bi-file-earmark-medical-fill me-2"></i>
          Doctor's Prescription
        </h3>
      </div>
      <div className="card-body">
        <div className="patient-info mb-4 p-3 bg-light rounded">
          <h4 className="d-flex align-items-center border-bottom pb-2 mb-3">
            <i className="bi bi-person-badge me-2 text-primary"></i>
            Patient Information
          </h4>
          <div className="row">
            <div className="col-md-6 mb-2">
              <div className="d-flex align-items-center">
                <i className="bi bi-person-fill text-secondary me-2"></i>
                <strong>Name:</strong>
                <span className="ms-2">{patientData?.name}</span>
              </div>
            </div>
            <div className="col-md-6 mb-2">
              <div className="d-flex align-items-center">
                <i className="bi bi-calendar-event text-secondary me-2"></i>
                <strong>Age:</strong>
                <span className="ms-2">{patientData?.age}</span>
              </div>
            </div>
            <div className="col-12">
              <div className="d-flex align-items-start">
                <i className="bi bi-clipboard2-pulse text-secondary me-2 mt-1"></i>
                <strong>Symptoms:</strong>
                <span className="ms-2">{patientData?.symptoms}</span>
              </div>
            </div>
          </div>
        </div>
        
        <div className="prescription-content mb-4">
          <h4 className="d-flex align-items-center border-bottom pb-2 mb-3">
            <i className="bi bi-capsule me-2 text-success"></i>
            Prescription
          </h4>
          <div className="prescription-text p-3 border rounded bg-light position-relative">
            <div className="prescription-watermark">
              <i className="bi bi-patch-check-fill text-success opacity-10"></i>
            </div>
            <pre style={{ whiteSpace: 'pre-wrap', fontFamily: 'inherit', position: 'relative', zIndex: 1 }}>
              {prescription}
            </pre>
          </div>
        </div>
        
        <div className="disclaimer mb-4 p-3 border-start border-warning border-4 bg-light rounded">
          <h5 className="d-flex align-items-center text-warning mb-2">
            <i className="bi bi-exclamation-triangle-fill me-2"></i>
            Medical Disclaimer
          </h5>
          <small>
            This prescription is generated by an AI assistant and is not a substitute for professional medical advice. 
            Please consult with a healthcare provider before following any recommendations.
          </small>
        </div>
        
        <div className="d-flex flex-wrap gap-2">
          <button
            className="btn btn-primary"
            onClick={onReset}
          >
            <i className="bi bi-arrow-counterclockwise me-2"></i>
            Start Over
          </button>
          
          <button 
            className="btn btn-outline-success"
            onClick={() => window.print()}
          >
            <i className="bi bi-printer-fill me-2"></i>
            Print Prescription
          </button>
          
          <button 
            className="btn btn-outline-secondary"
            onClick={() => {
              const blob = new Blob([prescription], { type: 'text/plain' });
              const url = URL.createObjectURL(blob);
              const a = document.createElement('a');
              a.href = url;
              a.download = `prescription_${patientData?.name || 'patient'}.txt`;
              a.click();
            }}
          >
            <i className="bi bi-download me-2"></i>
            Download Prescription
          </button>
        </div>
      </div>
    </div>
  );
}

export default Prescription; 